branch-defaults:
  default:
    environment: staging3
  master:
    environment: null
    group_suffix: null
environment-defaults:
  staging3:
    branch: null
    repository: origin
global:
  application_name: chat-republic
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:ca-central-1::platform/Puma with Ruby
    2.6 running on 64bit Amazon Linux/2.10.2
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application
