branch-defaults:
  master:
    environment: DemoApplication1-env
environment-defaults:
  DemoApplication1-env:
    branch: null
    repository: null
global:
  application_name: Demo-Application-1
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ca-central-1::platform/Puma with Ruby
    2.6 running on 64bit Amazon Linux/2.10.2
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
