development:
  adapter: async

test:
  adapter: test

production:
  #adapter: postgresql
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL"){ "redis://localhost:6379/1" } %>
  channel_prefix: chat_republic_1_production
